export const events = [
  {
    slug: "gracie-guard-mastery-2024",
    image: "/images/event1.png",
    title: "Gracie Guard Mastery Seminar",
    location: "San Diego, CA",
    date: "March 15, 2024",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "nogi-summit-texas",
    image: "/images/event2.png",
    title: "No-Gi Summit Texas",
    location: "Austin, TX",
    date: "April 22, 2024",
    time: "10:00 AM - 5:00 PM",
  },
  {
    slug: "bjj-world-open-nyc",
    image: "/images/event3.png",
    title: "BJJ World Open",
    location: "New York, NY",
    date: "May 8, 2024",
    time: "8:30 AM - 7:00 PM",
  },
  {
    slug: "submission-hunters-weekend",
    image: "/images/event4.png",
    title: "Submission Hunters Weekend Camp",
    location: "Seattle, WA",
    date: "June 14-16, 2024",
    time: "48 Hours",
  },
  {
    slug: "florida-jiu-jitsu-retreat",
    image: "/images/event5.png",
    title: "Florida Jiu-Jitsu Retreat",
    location: "Miami, FL",
    date: "July 20, 2024",
    time: "6:00 PM - 9:00 PM",
  },
  {
    slug: "mount-control-intensive",
    image: "/images/event6.png",
    title: "Mount Control Intensive",
    location: "Denver, CO",
    date: "August 12, 2024",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "chicago-open-gi-championship",
    image: "/images/event1.png",
    title: "Chicago Open Gi Championship",
    location: "Chicago, IL",
    date: "September 5, 2024",
    time: "8:00 AM - 5:30 PM",
  },
  {
    slug: "nogi-leglock-lab",
    image: "/images/event2.png",
    title: "No-Gi Leg Lock Lab",
    location: "Los Angeles, CA",
    date: "October 18, 2024",
    time: "9:30 AM - 6:00 PM",
  },
  {
    slug: "boston-guard-retention-camp",
    image: "/images/event3.png",
    title: "Boston Guard Retention Camp",
    location: "Boston, MA",
    date: "November 2, 2024",
    time: "8:00 AM - 7:00 PM",
  },
  {
    slug: "california-bjj-weekender",
    image: "/images/event4.png",
    title: "California BJJ Weekender",
    location: "San Diego, CA",
    date: "December 7-9, 2024",
    time: "72 Hours",
  },
  {
    slug: "oregon-open-mat-tour",
    image: "/images/event5.png",
    title: "Oregon Open Mat Tour",
    location: "Portland, OR",
    date: "January 15, 2025",
    time: "6:30 PM - 9:00 PM",
  },
  {
    slug: "nashville-grappling-summit",
    image: "/images/event6.png",
    title: "Nashville Grappling Summit",
    location: "Nashville, TN",
    date: "February 28, 2025",
    time: "9:00 AM - 5:00 PM",
  },
];
